language: node_js
node_js:
  - "8"

sudo: false

before_script:
  - npm install
cache:
  directories:
    - "node_modules"
script:
  - npm run coverage

after_success:
  - bash <(curl -s https://codecov.io/bash)